site_name: Uvicorn Korean
site_description: The lightning-fast ASGI server.

theme:
  name: "material"
  custom_dir: docs/overrides
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  features:
    - content.code.copy


repo_name: encode/uvicorn
repo_url: https://github.com/encode/uvicorn
edit_uri: ""

nav:
  - 소개: "index.md"
  - 설정: "settings.md"
  - 배포: "deployment.md"
  - 서버 작동 방식: "server-behavior.md"
  - 기여하기: "contributing.md"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

